name: CI

on: [push, pull_request]

env:
  DATABASE_URL: "https://fake.com"

jobs:
  build:

  runs-on: ubuntu-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      uses: npm install

    - name: Typecheck
      uses: npm run typecheck

    - name: lint
      uses: npm run lint
